// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ljN3RMySqPD_6hAhs9CGoN5B2ojdeJE',
    appId: '1:785851675943:web:d03c72d72ec913a7a5a502',
    messagingSenderId: '785851675943',
    projectId: 'chat-app-cf277',
    authDomain: 'chat-app-cf277.firebaseapp.com',
    storageBucket: 'chat-app-cf277.firebasestorage.app',
    measurementId: 'G-CD41VF6C40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGK652_b_EXcGr7RZQKj79sW6p6ekKRIE',
    appId: '1:785851675943:android:b61a8d830bd671e8a5a502',
    messagingSenderId: '785851675943',
    projectId: 'chat-app-cf277',
    storageBucket: 'chat-app-cf277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xSaPHCLvJ3Qrs8H9VOhGYGi9vADLnGQ',
    appId: '1:785851675943:ios:335c7bd94eb4ec83a5a502',
    messagingSenderId: '785851675943',
    projectId: 'chat-app-cf277',
    storageBucket: 'chat-app-cf277.firebasestorage.app',
    iosBundleId: 'com.example.k',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4xSaPHCLvJ3Qrs8H9VOhGYGi9vADLnGQ',
    appId: '1:785851675943:ios:335c7bd94eb4ec83a5a502',
    messagingSenderId: '785851675943',
    projectId: 'chat-app-cf277',
    storageBucket: 'chat-app-cf277.firebasestorage.app',
    iosBundleId: 'com.example.k',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4ljN3RMySqPD_6hAhs9CGoN5B2ojdeJE',
    appId: '1:785851675943:web:51d5b198d94ffb98a5a502',
    messagingSenderId: '785851675943',
    projectId: 'chat-app-cf277',
    authDomain: 'chat-app-cf277.firebaseapp.com',
    storageBucket: 'chat-app-cf277.firebasestorage.app',
    measurementId: 'G-0BDBSB6NVB',
  );
}
